services:
  apache:
    build:
      context: ./apache
    volumes:
      - ../src:/var/www/html
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest

volumes:
  mysql-data:
